export const ActionTypes={
    SET_USER : "SET_USER",
    GET_USER: "GET_USER",
    SET_DAILY_CALORIES:"SET_DAILY_CALORIES",
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    SET_REMAINING_CALORIES:"SET_REMAINING_CALORIES",
    FILTER_ITEMS:"FILTER_ITEMS",
    SORT_BY_HIGHEST:"SORT_BY_HIGHEST",
    SORT_BY_LOWEST:"SORT_BY_LOWEST"
}